version: "3"
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: todolist
        container_name: todolist-app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - todolist
        depends_on:
            - db
    db:
        image: mysql:8.0
        container_name: todolist-database
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
            - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
            - db_data:/var/lib/mysql
        networks:
            - todolist
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: todolist-phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        ports:
            - 8080:80
        depends_on:
            - db
        networks:
            - todolist
    nginx:
        image: nginx:alpine
        container_name: todolist-nginx
        restart: unless-stopped
        tty: true
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - todolist
networks:
    todolist:
        driver: bridge
volumes:
    db_data: ~
